### ISSUE TITLE
Inconsistent I2C address of the VCONN INA237 + CC1/CC2 connection

### ISSUE THREAD

**Issue by Hueburtsonly** [dojoe/Twonkie#11]
Firstly, thanks so much for designing this board -- I especially appreciate the enhancements over the original Twinkie with higher supported VBUS and dedicated BOOT pushbutton!

1. The VCONN INA237 has both A0 and A1 pulled up to 3V3 -- according to the [INA237 datasheet](https://www.ti.com/lit/ds/symlink/ina237-q1.pdf), this would give an I2C address of 1000101, i.e. 0x45 -- but the schematic labels the chip as 0x43. Is this just a typo on the schematic, or am I misunderstanding something?
2. In any case, the original Twinkie* uses an address of 0x41 for the VCONN INA237 -- just wondering why this was changed to 0x43/0x45 in your design?
3. Similarly, the chip is monitoring CC2 (pin B5) in the original Twinkie, but CC1 (pin A5)  in your design -- again, I understand that it's a bit of an arbitrary decision given the flippability of USB-C, but just curious if I'm missing any further context for this design choice (or if it is somehow connected to the address change above?)

Thanks again!

\* The hardware design for the original Twinkie is actually still available btw, even though the link to it was deleted from the Chromium page: https://www.chromium.org/chromium-os/twinkie/chromium-os-twinkie-v2.tar.bz2

**Comment by dojoe** [comment]
Hey - thanks for the kind words and sorry about the late response :/

1. Yep, it's a typo - the code uses 0x45 on v2: https://github.com/dojoe/Twonkie/blob/master/fw/board/twinkie/board.c#L64 - I'll fix the schematic, thanks for noticing!
2. That area of the board is pretty jammed, and pulling both pins the same way needed one less via :)
3. I honestly don't remember any more :) It might have been easier to route for some reason but it might just as well have been arbitrary when I reimplemented the original schematic.

Also I did mirror those hardware files into this repo when I started the project, so they're safe :) See https://github.com/dojoe/Twonkie/tree/master/ref/twinkie
