### ISSUE TITLE
Microcontroller part number is ambiguous

### ISSUE THREAD

**Issue by kristinpaget** [dojoe/Twonkie#3]
In the microcontroller part in the schematic, the field "Mfg P/N" is listed as "STM32F042C6T6TR" with a library reference of "STM32F042C6Tx" and a value of "STM32F072CB".  The BoM in hw/v1.0/twonkie.bom.csv reflects this as well, even the Digikey P/N points to the F042.  It would be preferable to switch to the STM32F072CBTx library part and P/Ns so that all four fields can remain consistent; I didn't notice the discrepancy until I tried to flash my otherwise fully-assembled units and realised I'd bought the wrong uC's.

**Comment by dojoe** [comment]
Oh crap - unit**s** even 😬 I'm very sorry about that! Hope it's not too much work to fix :/

That's a remnant from when I thought I could pull this off with an F042 - until Vincent made me aware they're using some of the F072's features which the F042 doesn't have. So I changed the value and called it a day, didn't even notice I had misleading part numbers all over the place.

I updated the schematics and BOM - thanks for reporting!
