### ISSUE TITLE
J2/EDAC_690-024-294T331_EdgeMount  Obsolete and no longer in stock

### ISSUE THREAD

**Issue by johnreitan** [dojoe/Twonkie#6]
What is a good replacement for EDAC_690-024-294T331_EdgeMount (151-1601-1-ND)?
Digikey suggests USB4070-30-C (2073-USB4070-30-CCT-ND) as a replacement, is this ok?

**Comment by dojoe** [comment]
Yes, I've ordered and tested that part for a build last year and it's a good replacement. I'll update the KiCad files and BOM.

**Comment by dojoe** [comment]
I updated the part number now - sorry it took so long. Once the `epr` branch gets merged this will show up in master too.
