### ISSUE TITLE
A sensor is out of stock

### ISSUE THREAD

**Issue by danielzfranklin** [dojoe/Twonkie#7]
The part [INA260AIPWR](https://www.digikey.com/en/products/detail/texas-instruments/INA260AIPWR/6590780) is out of stock on DigiKey and Mouser. Mouser lists the estimated restocking time as a bit less than a year.

Based on github activity I suspect you aren't currently updating this project. If you are, I thought this might be useful.

**Comment by dnschneid** [comment]
A lot of components are out of stock right now.  You may be able to find it with an alternative supplier, such as one listed in [Octopart](https://octopart.com/ina260aipwr-texas+instruments-75199489?r=sp) (see the non-authorized category).

**Comment by dojoe** [comment]
I am working on replacing the INA260 with an INA237 in the background, but since that requires an external shunt I am running into a lot of routing issues, and I don't have much time to devote to fixing those (and growing the board is out of the question, I have my principles! ☝️ ). One day! ;)

**Comment by danielzfranklin** [comment]
Thanks everyone. (I'm assuming the $50-$90 per is the plausible price, and the $4-$10 is definitely a scam @dnschneid.)

**Comment by dnschneid** [comment]
[MSRP from TI](https://www.ti.com/product/INA260/part-details/INA260AIPWR) is $4 in single unit quantities, so the larger numbers you're seeing are due to scalping.

**Comment by gidoBOSSftw5731** [comment]
Sorry to use an old thread but the part is still wildly out of stock and, although I have sent in RFQ to a few distributors on octopart, I'm not super optimistic. Is there another chip that could work instead? Could a board redesign happen somehow? (I work in software not circuits usually so I don't really know how hard that would be)

**Comment by dojoe** [comment]
No worries, I mean it's not like the shortage problem has been resolved by now :) I _have_ started designing an updated Twonkie that uses the INA237, mainly to resolve #4, but it's an on-and-off effort and pretty tricky to fit into the tight 1in x 1in envelope I have set myself, so I have not been successful yet. That said, your post might give me the motivation I need to take another crack at it :)

**Comment by dojoe** [comment]
(fwiw the 237 is also out of stock but at least mouser claims having some incoming in november 😅 )

**Comment by gidoBOSSftw5731** [comment]
I was taking a poke at https://github.com/gregdavill/PD-sniffer and the chip they use (an INA321 I think) isn't backordered, if that's of any use to you. I don't think it would solve the voltage issue in #4 but being able to test things before 2024Q4 (which was one estimate I got lol) would be nice.

**Comment by dojoe** [comment]
If it's any help, I am making a lot of progress on #4 and at the time I'm typing this DigiKey actually have a few of the 237s in stock :) The INA228 and INA238 appear to be possible drop-in replacements for the 237 too, and Mouser has a bunch of the 228 incoming in April.
Oh, and Mouser has 30 INA260s in stock right now, so if you're quick you may get lucky :)

**Comment by dojoe** [comment]
Twonkie v2 is out now, with an INA237 which has two compatible drop-in replacement parts.
